name: kube-score CI

on: push
jobs:
  kubeval:
    runs-on: ubuntu-latest
    steps:
      #kube-score action
    - name: Checkout
      uses: actions/checkout@v2
    - name: kube-score check
      uses: piraces/kube-score-ga@v0.1.3
      with:
        manifests-folders: './manifests/*.yaml'
